version: '3'

services:
  telegram-voice-transcriber:
    image: belgradebc/telegram-voice-transcriber:latest
    container_name: voice-transcriber
    restart: always
    volumes:
      - /volume2/docker-data/telegram-voice-transcriber/data:/app/data
      - /volume2/docker-data/telegram-voice-transcriber/.env:/app/.env